### ISSUE TITLE
Spline Interpolation pbroblem

### ISSUE THREAD

**Issue by NansSimpson** [cmdty/curves#16]
@cmdty 
Hello,
Thanks a lot for your work.
In your tutorial, you mention Spline Interpolation used for input contracts that have gaps. But in you example (see below) there is no gap. 
However, if I change the first contract with date(2019, 5, 15), 34.875) instead of date(2019, 5, 31), 34.875), I do create a gap. And the result of that seems completly wrong (see the remaining days of may: price going up before decreasing).
Could you have a look at that?

![image](https://user-images.githubusercontent.com/24104411/102247489-4ed40600-3f00-11eb-89f6-b932f6e3c4d4.png)

from curves import max_smooth_interp
from curves import contract_period as cp

contracts = [
    (date(2019, 5, 31), 34.875), 
    (date(2019, 6, 1), date(2019, 6, 2), 32.87),
    ((date(2019, 6, 3), date(2019, 6, 9)), 32.14),
    (pd.Period(year=2019, month=6, freq='M'), 31.08),
    (cp.month(2019, 7), 29.95),
    (cp.q_3(2019), 30.18),
    (cp.q_4(2019), 37.64),
    (cp.winter(2019), 38.05),
    (cp.summer(2020), 32.39),
    (cp.winter(2020), 37.84),
    (cp.gas_year(2020), 35.12)
]

pc_for_spline, bc_for_spline = bootstrap_contracts(contracts, freq='D')
smooth_curve = max_smooth_interp(bc_for_spline, freq='D')

%matplotlib inline
pc_for_spline.plot(legend=True)
ax = smooth_curve.plot(legend=True)
ax.legend(["Piecewise Daily Curve", "Smooth Daily Curve"])

**Comment by cmdty** [comment]
Hi @NansSimpson when you say the results "seem completely wrong" I presume it means that it isn't what you expect, rather than it breaches the conditions of the spline, as described in the [technical documention](https://github.com/cmdty/curves/blob/master/docs/max_smoothness/max_smoothness_spline.pdf). In cases like this, you have to remember that max_smooth_interp is just a dumb algorithm, it only knows to solve the mathematical constraints which include maximising the smoothness. Hopefully the results of this algorithm match up to what one would expect, and common sense given commodity forward curve behaviour (otherwise it would be pretty useless), but unfortunately this isn't always the case. Generally, the more information you give the algorithm, the better the output matches what you would expect to be sensible, so in the case of the gap you are taking away some information. If you want to control the shape, you can add some more information, for example I just tried to use the front_1st_deriv parameter to max_smooth_interp to control the shape at the front over the gap, although not with much success. Maybe in a practical situation where you have a gap in the contracts, the best way is to fill the gap using the bootstrap_contracts function and a shaping spread/ratio based on historical analysis or your opinion.

**Comment by NansSimpson** [comment]
Hi @cmdty !
Thanks a lot for your reply! I totally understand what you mean. Will try to play with parameters.
In case things were not very clear: I am trying to smooth near gas curve. So I basically have day-ahead contract and then front month. So I will always have a gap in between. (I don't always have the BOM contract available). So you are saying that I should probably try to build the BOM contract myself. I can do that, but I am a bit disappointed because I thought that I could get the BOM value out of this algo.

**Comment by cmdty** [comment]
Hi @NansSimpson, OK interpolating the BOM price makes sense and I can see why you might want to use the curves package for this. However, I suspect it won't be possible to work well consistently. You might want to try deriving the front_1st_deriv argument using some logic like (front_month_price - da_price)/(num_days_to_front_month_start - 1)/365.0, i.e. using the gradient between DA and BOM prices. But I'm not sure this will work well, especially considering the the DA price could spike. I would suggest a more promising approach could be applying some sort of exponential decay from the DA price to the front month price which could work well in the presence of price spikes.

**Comment by NansSimpson** [comment]
@cmdty 
Thanks again for your time!
I understand the logic with the _front_1st_deriv_ argument but I can't get it working. 
If you could show me an example with the _front_1st_deriv_ argument (the simple gradient would be enough for me first), it would be awesome! I hope I am not bothering.

**Comment by cmdty** [comment]
Just tried this and it didn't work very well. See the code below.

from curves import contract_period as cp

da_contract = date(2019, 5, 15)
da_price = 34.875
ma_start = date(2019, 6, 1)
ma_price = 32.87

da_to_ma_slope = (ma_price - da_price)/((ma_start - da_contract).days + 1)/365.0

contracts = [
(da_contract, da_price),
(ma_start, date(2019, 6, 2), 32.87),
((date(2019, 6, 3), date(2019, 6, 9)), 32.14),
(pd.Period(year=2019, month=6, freq='M'), ma_price),
(cp.month(2019, 7), 29.95),
(cp.q_3(2019), 30.18),
(cp.q_4(2019), 37.64),
(cp.winter(2019), 38.05),
(cp.summer(2020), 32.39),
(cp.winter(2020), 37.84),
(cp.gas_year(2020), 35.12)
]

pc_for_spline, bc_for_spline = bootstrap_contracts(contracts, freq='D')
smooth_curve = max_smooth_interp(bc_for_spline, freq='D', front_1st_deriv=da_to_ma_slope)

%matplotlib inline
pc_for_spline.plot(legend=True)
ax = smooth_curve.plot(legend=True)
ax.legend(["Piecewise Daily Curve", "Smooth Daily Curve"])
