### ISSUE TITLE
Overlapping contracts

### ISSUE THREAD

**Issue by Jidvei** [cmdty/curves#20]
Hi,

First of all, thanks for your great piece of work!

I'm trying to understand two things about the spline methodology, while reading Benth (2008).
It seems that the library here does not utilize equation 9 (1st deriative of t_n =0). Can you some shed some light on this? I'd assume that it would be part of the constraint matrix.

Moreover, Benth describes the knots to support overlapping periods, which is quite key in power markets with monthly/quarterly/yearly contracts overlapping. I'm trying to understand the amendments you've made (I can see that the dimensions of the B vector along with the A constraintmatrix differ), and I'd like to contribute to adding this element. 
In order to obtain the dimensions specified in Benth (A = 3n + (m-2) x 5n), wouldn't it require 2 knots when we go from one contract to another (whereas it is one point in this implementation if I understood correctly), i.e. T_1^e != T_2^s

![image](https://user-images.githubusercontent.com/43203488/191523445-937bfa0f-cf4a-4e28-976d-28746e5a1149.png)

**Comment by cmdty** [comment]
The spline algorithm in Cmdty.Curves is more flexible than that specified in the Benth paper because it give you the flexibility to control the first derivative at the start and end of the curves as:
- Any number which the caller can specify. So you can choose this to be zero if you want to match the Benth paper.
- Leave it unspecified, in which case the algorithm just finds the max smoothness curve without this constraint.

You can see this in the source code. See the arguments frontFirstDerivative and backFirstDerivative on line 117 of [MaxSmoothnessSplineCurveBuilder.cs](https://github.com/cmdty/curves/blob/master/src/Cmdty.Curves/MaxSmoothness/MaxSmoothnessSplineCurveBuilder.cs).
The problem here is that I didn't include this in the spline technical document! Maybe some time I'll get around to adding this.

By design bootstrapping out the prices of non-overlapping elements has been separated out from the spline in the curves library for a number of reasons:
- Allows callers to get access to piecewise flat bootstrapped curves without having to do the full spline algorithm. Piecewise flat curves are still useful for many purposes.
- Makes it easy to understand the numbers output by the spline as you can view the intermediate step of bootstrapped prices, whereas if the bootstrapping is done as part of the spline calculation it is harder to reason with the output. Surprisingly the bootstrapping calc can be unstable and give some crazy numbers in some situations. If this bootstrapping was done at the same time as the spline interpolation it would be very difficult to understand, or rectify this.
- Easier to test and spot bugs, mostly for the reasons given in the above point.

@Jidvei if you like the work please give the project a star on GitHub!
