### ISSUE TITLE
Optimise with contracts overlapping month periods

### ISSUE THREAD

**Issue by jsenergy** [cmdty/curves#8]
I am running into a problem when including a contract which has a period that overlaps a month change. In this example this would be Wk18-2020.

```
 # Day contracts
 (datetime.date(2020, 4, 3), datetime.date(2020, 4, 3), 18.02),
 (datetime.date(2020, 4, 6), datetime.date(2020, 4, 6), 12.73),
 # Week contracts
 (datetime.date(2020, 4, 6), datetime.date(2020, 4, 12), 16.0),
 (datetime.date(2020, 4, 13), datetime.date(2020, 4, 19), 16.78),
 (datetime.date(2020, 4, 20), datetime.date(2020, 4, 26), 20.82),
 (datetime.date(2020, 4, 27), datetime.date(2020, 5, 3), 17.97), # This is what is causing issues
 # Month contracts
 (datetime.date(2020, 5, 1), datetime.date(2020, 5, 31), 22.21),
 (datetime.date(2020, 6, 1), datetime.date(2020, 6, 30), 27.3)
```

While output prices are correct for the average of the peak week, the distribution within the week is less than ideal. See below:

```
27/04/2020 | 13.65808
28/04/2020 | 13.65808
29/04/2020 | 13.65808
30/04/2020 | 13.65808
01/05/2020 | 35.21769
```

Is there any way to force these shapes when already using an average_weight function for peaks?

Attaching a notebook for your benefit.

Many thanks

[Month overlap.ipynb.zip](https://github.com/cmdty/curves/files/4421606/Month.overlap.ipynb.zip)

**Comment by jsenergy** [comment]
Adding a balance of month contract helps in this case, but is there a way to still profile the days in the week without providing a BOM value? 

```
 # Balance of Month contracts
 (datetime.date(2020, 4, 2), datetime.date(2020, 4, 30), 18.01), 
```

**Comment by cmdty** [comment]
I'll take a look at this in the next couple of days.

**Comment by cmdty** [comment]
Hi @jsenergy, I've taken a look, and this sort of situation can often cause a result which doesn't look correct. The problem is that the algorithm is calculating the least-squares solution, but the problem is that it sometimes doesn't look correct. In these cases, as you alluded to, you need to add more information to the algorithm. See that attached notebook where I've added a ratio constraint.
[Month overlap ratio.zip](https://github.com/cmdty/curves/files/4425373/Month.overlap.ratio.zip)

**Comment by cmdty** [comment]
From memory this problem is recurs in the situation where:
- There is contract 1 spans the period where contracts 2 ends and contract 3 starts.
- Contract 1 does not start at the same time as contract 2.
- There does not exists a sequence of contiguous contracts which end at the start of contract 1 and start at the beginning of contract 2.

In most situations this doesn't occur because of the way days, months, quarters, season and calendar years join together, and the fact that contracts drop off as maturity increases. However, where you will see this problem is:
- With weeks, as you've seen. Because of the third point above it won't happen if you're lucky and a week starts on the first of a month.
- Also with weekend contracts which span 2 different months.

The only way I can think of dealing with it is to use the bootstrap shaping factors as in the notebook. It's unfortunate as it will complicate the code which feeds the bootstrapper.

**Comment by jsenergy** [comment]
Thanks for the summary. 

Let me think of how I can incorporate a logic to add shaping_ratios when the above problematic conditions are met.

**Comment by cmdty** [comment]
@jsenergy this issue has got a better resolution in curves package version 1.1.0.

**Comment by jsenergy** [comment]
Thank you, will look at this in the coming weeks!
