### ISSUE TITLE
sum of weighting evaluated to non-positive number

### ISSUE THREAD

**Issue by jsenergy** [cmdty/curves#9]
Hi, it's me again with yet another bootstrap problem...

Currently using the mult_season_adjust in the max_smooth_interp function to generate sensible shapes for quarters relative to the year, months/qtr, days/month and I am running into an error.

I start with contracts of the lowest granularity (years and qtr) to generate a strip of quarters with ratios that i like based on my calibration/historical analysis. However, when I try to use these quarterly values together with any monthly values I have, _bootstrap_contracts_ throws the following error:

`ArgumentException: sum of weighting evaluated to non-positive number for the following contract: Start: 2020-05, End: 2020-05, Price: 24.77`

I am using a peak weighting in the example that fails. The offpeak weighting computes properly, which leads me to believe that the optimiser does not like the combination of (start_dt, end_dt, price) and (pd.Period(), price) contract types.

Attaching a notebook for your benefit. 
[weighting issues.ipynb.zip](https://github.com/cmdty/curves/files/4533074/weighting.issues.ipynb.zip)

**Comment by cmdty** [comment]
In situations like this, in order to investigate what's going on you should try evaluating the weighting function with the inputs like in the attached notebook. This shows the weighting is zero for 2020-05 which is because the weighting function doesn't work for non-daily frequencies. As you'll see in the attached notebook. Also I've tried using the weighting function found in the curves_tutorial notebook (and which you previously found doesn't work well with daily granularity) and it appears to work ok.
[weighting issues.zip](https://github.com/cmdty/curves/files/4534803/weighting.issues.zip)

**Comment by jsenergy** [comment]
Should have figured that out myself! Thanks for the swift turnaround.
